Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../organizations/ordererOrganizations/example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        OrdererEndpoints:
            - orderer.example.com:7050
    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: ../organizations/peerOrganizations/org1.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org1MSP.peer')"
        AnchorPeers:
          - Host: peer0.org1.example.com
            Port: 7051
    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: ../organizations/peerOrganizations/org2.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org2MSP.peer')"
        AnchorPeers:
          - Host: peer0.org2.example.com
            Port: 9051
    - &cau
        Name: cauMSP
        ID: cauMSP
        MSPDir: ../organizations/peerOrganizations/cau.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('cauMSP.admin', 'cauMSP.peer', 'cauMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('cauMSP.admin', 'cauMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('cauMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('cauMSP.peer')"
        AnchorPeers:
          - Host: peer0.cau.example.com
            Port: 10051

    - &soft
        Name: softMSP
        ID: softMSP
        MSPDir: ../organizations/peerOrganizations/soft.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('softMSP.admin', 'softMSP.peer', 'softMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('softMSP.admin', 'softMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('softMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('softMSP.peer')"
        AnchorPeers:
          - Host: peer0.soft.example.com
            Port: 12051

    - &LG
        Name: LGMSP
        ID: LGMSP
        MSPDir: ../organizations/peerOrganizations/LG.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('LGMSP.admin', 'LGMSP.peer', 'LGMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('LGMSP.admin', 'LGMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('LGMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('LGMSP.peer')"
        AnchorPeers:
          - Host: peer0.LG.example.com
            Port: 13051


Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer.example.com:7050
    EtcdRaft:
        Consenters:
        - Host: orderer.example.com
          Port: 7050
          ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *cau
                    - *soft
                    - *LG
    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *cau
                - *soft
                - *LG
            Capabilities:
                <<: *ApplicationCapabilities
